[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
monitor_filters = direct
board_upload.flash_size = 4MB
board_build.esp-idf.sdkconfig_path = sdkconfig.lolin_s2_mini
build_flags =
  -DUSB_VID=0x0F0D
  -DUSB_PID=0x00C1
  -DUSB_MANUFACTURER="\"HORI CO.,LTD.\""
  -DUSB_PRODUCT="\"HORIPAD S\""
